### ISSUE TITLE
Docu doesn't match current version

### ISSUE THREAD

**Issue by ArenzD** [industrial-edge/upload-app-to-industrial-edge-management#6]
# Issue-template

## Summary

Dokumention doesn't match with current version.

## Version of the used components

Which versions of the Industrial Edge components did you use?
- Industrial Edge Management V1.7.4

## Steps to reproduce

Follow [guide ](https://github.com/industrial-edge/upload-app-to-industrial-edge-management) compare docu with current version system.

## What is the current bug behavior?

Docu not up to date.

## What is the expected correct behavior?

Up to date docu.

## Relevant logs and/or screenshots

Docu:

![image](https://user-images.githubusercontent.com/88773196/180380709-d14fb985-a992-48d9-be48-604ff9794da0.png)

Current Version:

![image](https://user-images.githubusercontent.com/88773196/180380478-d19fde61-9c3c-438d-b0db-7d28b7fcec15.png)

**Comment by HummelN7872** [comment]
@ArenzD thanks for creating the bug, I will put it to the work items to update the docu to the current versions

**Comment by EndyCZ** [comment]
For Maintenance reasons, we will convert the GIF into several pictures so that we are flexible in the future to adjust the documentation.

**Comment by EndyCZ** [comment]
Fixed by https://github.com/industrial-edge/upload-app-to-industrial-edge-management/commit/58e438a8d987ae92393e47f80cd105c4c1334e92
